INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('alex' , '$2a$04$qbfuI3SWUGGKEira.wX3iep4WqnvjM6GBBFsP0DT2SYzzQMVZvqd2' , 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user' , '$2a$04$2d1DdAaPHMP9n9psiRUoo.dOci1Ii9qaG5CemMhAtH2J0RxhymFLW' , 1);


INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('alex' , 'ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('alex' , 'USER');


INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user' , 'USER');



