INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('alex' , 'admin' , 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user' , 'user' , 1);


INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('alex' , 'ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('alex' , 'USER');


INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user' , 'USER');



